// Hirotoli Home error codes (Phase 1 foundation).
// Frontend maps codes to human-readable messages; never match on message strings.

export const HOME_ERROR_CODES = [
  'HOME_FULL',
  'ALREADY_IN_HOME',
  'TARGET_ALREADY_IN_HOME',
  'USER_ALREADY_IN_ANOTHER_HOME',
  'TARGET_OFFLINE',
  'INVITATION_EXPIRED',
  'INVITATION_ALREADY_RESPONDED',
  'INVITATION_ALREADY_PENDING',
  'INVITATION_NOT_FOUND',
  'INVITATION_ACTION_NOT_ALLOWED',
  'INVITATION_LIMIT_REACHED',
  'CANNOT_INVITE_SELF',
  'JOIN_REQUEST_EXPIRED',
  'JOIN_REQUEST_ALREADY_RESPONDED',
  'JOIN_REQUEST_ALREADY_PENDING',
  'JOIN_REQUEST_NOT_FOUND',
  'JOIN_REQUEST_ACTION_NOT_ALLOWED',
  'JOIN_REQUEST_LIMIT_REACHED',
  'TARGET_HAS_NO_HOME',
  'CANNOT_REQUEST_SELF',
  'VOICE_UNAVAILABLE',
  'HOME_DISABLED',
  'NOT_A_CONNECTION',
  'NOT_HOME_MEMBER',
  'NOT_HOME_OWNER',
  'HOME_DESTROYED',
  'HOME_NOT_FOUND',
  'CANNOT_REMOVE_SELF',
  'USER_UNAVAILABLE',
] as const;

export type HomeErrorCode = (typeof HOME_ERROR_CODES)[number];
